import { StyleSheet } from "react-native";

export const createPanelStyles = (theme) => StyleSheet.create({
  panel: { gap: 18 },
  title: { color: theme.text, fontSize: 22, fontWeight: "700" },
  section: { gap: 12, backgroundColor: theme.surfaceAlt, padding: 18, borderRadius: 8 },
  sectionTitle: { color: theme.text, fontSize: 16, fontWeight: "700" },
  card: { backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, padding: 14, borderRadius: 8, gap: 10 },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  text: { color: theme.text, fontSize: 14 },
  muted: { color: theme.textSecondary, fontSize: 14 },
  input: { minHeight: 42, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 6, color: theme.text, paddingHorizontal: 12 },
  inputButton: { minHeight: 42, justifyContent: "center", backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 6, paddingHorizontal: 12 },
  placeholderText: { color: theme.textSecondary },
  fieldLabel: { color: theme.textSecondary, fontSize: 13, fontWeight: "600" },
  multiline: { minHeight: 90, paddingTop: 12, textAlignVertical: "top" },
  primaryButton: { backgroundColor: theme.accent, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 6, alignItems: "center" },
  primaryButtonText: { color: theme.surface, fontWeight: "700" },
  secondaryButton: { backgroundColor: theme.drawerActive, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 6, alignItems: "center" },
  secondaryButtonText: { color: theme.text, fontWeight: "600" },
  dangerButton: { borderWidth: 1, borderColor: theme.accent, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 6, alignItems: "center" },
  dangerText: { color: theme.accent, fontWeight: "700" },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  empty: { color: theme.textSecondary, textAlign: "center", paddingVertical: 28 },
  badge: { color: theme.text, backgroundColor: theme.drawerActive, paddingVertical: 4, paddingHorizontal: 8, borderRadius: 4, overflow: "hidden", fontSize: 12, fontWeight: "700" },
  pagination: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 14 },
  disabledButton: { opacity: 0.4 },
  modalBackdrop: { flex: 1, justifyContent: "center", padding: 20, backgroundColor: "rgba(0, 0, 0, 0.65)" },
  modalCard: { maxWidth: 520, width: "100%", alignSelf: "center", gap: 14, backgroundColor: theme.surface, padding: 20, borderRadius: 12 },
  modalOption: { padding: 12, borderBottomWidth: 1, borderBottomColor: theme.border },
  imagePicker: { minHeight: 120, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.border, borderRadius: 6, padding: 12 },
  imagePreview: { width: "100%", height: 150, borderRadius: 6 },
});